services:
    mysql:
        image: mysql:8.0.39
        container_name: mysql
        ports:
            - "${MYSQL_PORT}:3306"
        env_file:
            - .env
        environment:
            MYSQL_ROOT_HOST: '%' # Allow connection from any host
        volumes:
            - mysql_data:/var/lib/mysql
        restart: unless-stopped

volumes:
    mysql_data:
